// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbContext.Migrations.PostgresDbContext
{
    [DbContext(typeof(MainDbContext.PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbModels.CreditCardDbM", b =>
                {
                    b.Property<Guid>("CreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedToken")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ExpirationMonth")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ExpirationYear")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Issuer")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("OwnerDbMOwnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Seeded")
                        .HasColumnType("boolean");

                    b.HasKey("CreditCardId");

                    b.HasIndex("OwnerDbMOwnerId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("DbModels.OwnerDbM", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("boolean");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("DbModels.CreditCardDbM", b =>
                {
                    b.HasOne("DbModels.OwnerDbM", "OwnerDbM")
                        .WithMany("CreditCardsDbM")
                        .HasForeignKey("OwnerDbMOwnerId");

                    b.Navigation("OwnerDbM");
                });

            modelBuilder.Entity("DbModels.OwnerDbM", b =>
                {
                    b.Navigation("CreditCardsDbM");
                });
#pragma warning restore 612, 618
        }
    }
}
